#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_diffusion = env_modules.Clone()

# Always build for desktop and mobile platforms that support RenderingServer
env_diffusion.add_source_files(env.modules_sources, "register_types.cpp")
env_diffusion.add_source_files(env.modules_sources, "diffusion_effect.cpp")


